language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
services:
  - redis-server
env:
  - RACK_ENV=redis
  - RACK_ENV=git
install:
  - bundle install

matrix:
  include:
    - rvm: jruby-19mode
      services: redis-server
      env: RACK_ENV=redis
      install: bundle install --without=git

#script:
#  - bundle exec rspec spec/

