language: ruby
rvm:
  - 1.9.3
services:
  - redis-server
env:
  - RACK_ENV=redis
  - RACK_ENV=git
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libxslt-dev
install:
  - bundle install

matrix:
  include:
    - rvm: jruby-19mode
      services: redis-server
      env: RACK_ENV=redis
      install: bundle install --without=git

#script:
#  - bundle exec rspec spec/

