language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
services:
  - redis-server
env:
  - RACK_ENV=redis
  - RACK_ENV=git
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev libxml2-dev libxslt-dev
install:
  - bundle install
#script:
#  - bundle exec rspec spec/
